---
codecov:
  branch: main
codecov:
  require_ci_to_pass: false
coverage:
  status:
    project: true
    patch: false
    project:
      default:
        target: 100%
        threshold: 1
        paths:
          - "demo"
