coverage:
  status:
    project: true
    codecov:   # status check name
      target: auto
      threshold: 5
      base: auto
      paths:
        - "demo"
      # advanced settings
      if_ci_failed: error #success, failure, error, ignore
      informational: false
      only_pulls: false
