dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

stages:
  - name: test
    if: |
      branch = master

jobs:
  include:
    - stage: test
      install:
        # command to install dependencies
        - pip install .

      script:
        # command to run tests
        - pytest tests/
