dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

stages:
  - name: test
    if: |
      branch = master

jobs:
  include:
    - stage: test
      # command to install dependencies
      install:
        - pip install .
      # command to run tests
      script:
        - pytest tests/
