dist: xenial

language: python
python:
  - "3.6"

stages:
  - test
  - name: conditional
    if: tag IS present

jobs:
  include:
    - stage: test
      install:
        - pip install -r requirements.txt .

      script:
        - python3 -m pytest tests/

    - stage: conditional
      script: echo "foo"
      deploy:
        provider: script
        script: echo "bar"
        on:
          branch: master
