name: Build Develop Images

on:
  push:
    branches: [ develop ]

jobs:
  test:
    uses: ./.github/workflows/test-package.yml
  build:
    name: build
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v2
      # Fetch all history for all tags and branches
      with:
        fetch-depth: 0

    - name: Build and push development docker image
      env:
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
      run: |
        export DOCKER_TAG=`git describe --tags --always`
        echo "${DOCKER_TAG}"
        echo "${REGISTRY_PASSWORD}" | docker login -u "${REGISTRY_USER}" --password-stdin;
        docker build -t ${REGISTRY_USER}/test:dev-${DOCKER_TAG} .
        docker push ${REGISTRY_USER}/test:dev-${DOCKER_TAG}
