name: Build Develop Images

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    # Test code
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt .
    - name: Test with pytest
      run: |
        python3 -m pytest tests/

    - name: Build and push development docker image
      run: |
        export DOCKER_TAG=`git describe --tags --always`
        echo "${REGISTRY_PASSWORD}" | docker login -u "${REGISTRY_USER}" --password-stdin;
        docker build -t ${REGISTRY_USER}/test:dev-${DOCKER_TAG}.
        docker push ${REGISTRY_USER}/test:dev-${DOCKER_TAG}
