name: Code Tests

on:
  push:
    branches-ignore: [ develop ]
  workflow_call:

jobs:
  test:
    name: pytest
    runs-on: ubuntu-18.04

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt .
    - name: Test with pytest
      run: |
        python3 -m pytest tests/
